-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 15:32:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dev_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dev_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev_db` DEFAULT CHARACTER SET utf8 ;
USE `dev_db` ;

-- -----------------------------------------------------
-- Table `dev_db`.`dev_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db`.`dev_admin` (
  `idev_admin` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `clave` TEXT(100) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idev_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db`.`dev_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db`.`dev_usuario` (
  `id_dev` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellido` VARCHAR(80) NOT NULL,
  `telefono` BIGINT(15) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `borrado` ENUM('v', 'f') NOT NULL DEFAULT 'v',
  `dev_admin_idev_admin` INT(10) NOT NULL,
  PRIMARY KEY (`id_dev`),
  CONSTRAINT `fk_dev_usuario_dev_admin`
    FOREIGN KEY (`dev_admin_idev_admin`)
    REFERENCES `dev_db`.`dev_admin` (`idev_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
